GET localhost:8060/api/order

### Send Order

GET localhost:8060/api/order/send

### Menu

GET localhost:8060/api/menu


### Post Valid Order

POST localhost:8060/api/order
Content-Type: application/json

{
  "cart": {
    "items": [
      {
        "itemId": "item-1",
        "itemTitle": "Spare Ribs",
        "count": 2,
        "itemPrice": 10.0,
        "total": 20.0
      }
    ]
  },
  "billingAddress": {
    "name": "Frank",
    "city": "Washington",
    "street": "Pennsylvania Avenue 1600",
    "zip": "12345"
  }
}
