### Hello Order

GET localhost:8060/


### Post Invalid Order

POST localhost:8060/api/order
Content-Type: application/json

{
  "cart": {
    "items": []
  },
  "billingAddress": {
  }
}


### Menu

GET localhost:8060/api/menu


### Menu filtered by Category Key

GET localhost:8060/api/menu/main-course/menu-items


### Challenge: Reduce Menu Item Price

PATCH localhost:8060/api/menu/menu-items/0da7f6f4-a472-4ff7-89e2-0e416942614c
Content-Type: application/json

{
  "price": 19.99
}


### Challenge: Delete Menu Item

DELETE localhost:8060/api/menu/menu-items/0da7f6f4-a472-4ff7-89e2-0e416942614c