name: freddy-bbq

services:

  shop-frontend:
     container_name: shop-frontend
     build: shop-frontend
     ports:
        - "4200:4200"

  order:
     container_name: order
     build: order
     environment:
       - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
     ports:
        - "8060:8060"

  delivery:
    container_name: delivery
    build: delivery
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8050:8050"

  kitchen:
     container_name: kitchen
     build: kitchen
     environment:
       - KITCHEN_KAFKASERVERS=kafka:9092
     depends_on:
      - order
     ports:
        - "8070:8070"

  kafka-zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - kafka-zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TOPIC_AUTO_CREATE: true

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: kafka-zookeeper:2181