name: freddys-bbq

services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
        - backend_order

  backend_order:
    container_name: Backend-Order
    build: Backend/order
    ports:
      - "8080:8080"

  backend_delivery:
    container_name: Backend-Delivery
    build: Backend/delivery
    ports:
      - "8081:8081"
    depends_on:
      - backend_order
