name: freddys-bbq

services:
  frontend:
    container_name: frontend
    build: frontend
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
        - backend

  backend:
    container_name: backend
    build: backend
    ports:
      - "8080:8080"
