name: freddy-bbq

services:

  shop-frontend:
     container_name: shop-frontend
     build: shop-frontend
     ports:
        - "4200:4200"

  order:
     container_name: order
     build: order
     environment:
       - SPRING_RABBITMQ_HOST=rabbitmq
     ports:
        - "8060:8060"

  delivery:
    container_name: delivery
    build: delivery
    depends_on:
      - order
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8050:8050"

  kitchen:
     container_name: kitchen
     build: kitchen
     environment:
       - KITCHEN_RABBITMQHOST=rabbitmq
     depends_on:
      - order
     ports:
        - "8070:8070"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
