name: freddys-bbq-release

services:
  freddys-bbq-main:
    container_name: Freddys-BBQ-Main
    build: .
    ports:
      - "8080:8080"
    environment:
      - ORDER_BACKEND_URL=http://freddys-bbq-main:8080
      - DELIVERY_BACKEND_URL=http://freddys-bbq-main:8080
      - INTERN_FRONTEND_URL=http://freddys-bbq-main:8080
      - CUSTOMER_FRONTEND_URL=http://freddys-bbq-main:8080
      - MAP_SERVICE_URL=http://map-service:8090

  map-service:
    container_name: Map-Service
    build: Backend/map
    ports:
      - "8090:8090"