name: freddys-bbq

services:
  frontend-customer:
    container_name: Frontend-Customer
    build: Frontend/customer
    ports:
      - "4200:4200"
    environment:
      - ORDER_BACKEND_URL=http://backend-order:8080
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081
      - INTERN_FRONTEND_URL=http://localhost:4300
    depends_on:
      - backend-order
      - backend-delivery
      
  frontend-intern:
    container_name: Frontend-Intern
    build: Frontend/Intern
    ports:
      - "4300:4300"
    environment:
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081
      - MAP_SERVICE_URL=http://map-service:8090
      - CUSTOMER_FRONTEND_URL=http://frontend-customer:4200
    depends_on:
        - backend-order
        - backend-delivery

  backend-order:
    container_name: Backend-Order
    build: Backend/order
    ports:
      - "8080:8080"
    environment:
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/orders
    depends_on:
      - postgres

  backend-delivery:
    container_name: Backend-Delivery
    build: Backend/delivery
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/orders
    depends_on:
      - backend-order
      - postgres

  #map-service:
  #  container_name: Map-Service
  #  build: Backend/map
  #  ports:
  #    - "8090:8090"

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - '5432:5432'