name: freddys-bbq

services:
  frontend-customer:
    container_name: Frontend-Customer
    build: Frontend/customer
    ports:
      - "4200:4200"
    environment:
      - ORDER_BACKEND_URL=http://backend-order:8080
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081
    depends_on:
      - backend-order
      - backend-delivery
      
  frontend-intern:
    container_name: Frontend-Intern
    build: Frontend/Intern
    ports:
      - "4300:4300"
    environment:
      - ORDER_BACKEND_URL=http://backend-order:8080
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081
    depends_on:
        - backend-order
        - backend-delivery

  backend-order:
    container_name: Backend-Order
    build: Backend/order
    ports:
      - "8080:8080"
    environment:
      - DELIVERY_BACKEND_URL=http://backend-delivery:8081

  backend-delivery:
    container_name: Backend-Delivery
    build: Backend/delivery
    ports:
      - "8081:8081"
    depends_on:
      - backend-order
