apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
        - name: kitchen
          image: kitchen:0.0.1
          ports:
            - containerPort: 8070
          # Umgebungsvariablen
          env:
            - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
              value: "true"