apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-frontend
  template:
    metadata:
      labels:
        app: shop-frontend
    spec:
      containers:
        - name: shop-frontend
          image: shop-frontend:0.0.1
          ports:
            - containerPort: 4200
