server:
  port: 8060
  # Problem Details without Stacktrace
  error:
    include-stacktrace: never

spring:
  application:
    name: order
management:
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,loggers,info
#  metrics:
#    tags:
#      service: kitchen

kitchen-service:
  url: http://localhost:8070

delivery-service:
  url: http://localhost:8060

# logging:
#  config: classpath:logback.xml