spring:
  application:
    name: delivery
  jackson:
    serialization:
      write-dates-as-timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

server:
  port: 8050

kitchen-service:
  url: http://localhost:8070