name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dos2unix
        run: sudo apt-get update && sudo apt-get install -y dos2unix

      - name: Convert gradlew to Unix format (LF) and Grant execute permission to Gradle Wrapper
        run: |
          find . -name "gradlew" -exec dos2unix {} \;
          find . -name "gradlew.bat" -exec dos2unix {} \;
          chmod +x Backend/delivery/gradlew
          chmod +x Backend/order/gradlew
          chmod +x Frontend/customer/gradlew
          chmod +x Frontend/Intern/gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Run Tests for Backend (Delivery & Order)
        run: |
          cd Backend/delivery && ./gradlew test && cd ../..
          cd Backend/order && ./gradlew test && cd ../..

      - name: Run Tests for Frontend (Customer & Intern)
        run: |
          cd Frontend/customer && ./gradlew test && cd ../..
          cd Frontend/Intern && ./gradlew test && cd ../..
