name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    # Currently not needed, uncomment if there is a need for a Postgres server
    #services:
    #  postgres:
    #    image: postgres:latest
    #    env:
    #      POSTGRES_USER: test
    #      POSTGRES_PASSWORD: test
    #      POSTGRES_DB: testdb
    #    ports:
    #      - 5432:5432
    #    options: >-
    #      --health-cmd "pg_isready -U test"
    #      --health-interval 10s
    #      --health-timeout 5s
    #      --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Run Tests for Backend (Delivery & Order)
        run: |
          cd Backend/delivery && ./gradlew test && cd ../..
          cd Backend/order && ./gradlew test && cd ../..

      - name: Run Tests for Frontend (Customer & Intern)
        run: |
          cd Frontend/customer && ./gradlew test && cd ../..
          cd Frontend/Intern && ./gradlew test && cd ../..
